-- MySQL Script generated by MySQL Workbench
-- Sat Jun 30 20:14:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema corpora1_franklinsgold
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corpora1_franklinsgold
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corpora1_franklinsgold` DEFAULT CHARACTER SET utf8 ;
USE `corpora1_franklinsgold` ;

-- -----------------------------------------------------
-- Table `corpora1_franklinsgold`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpora1_franklinsgold`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corpora1_franklinsgold`.`origen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpora1_franklinsgold`.`origen` (
  `idorigen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idorigen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corpora1_franklinsgold`.`moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpora1_franklinsgold`.`moneda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fecha_elaboracion` VARCHAR(15) NOT NULL,
  `diametro` FLOAT NOT NULL,
  `espesor` FLOAT NOT NULL,
  `composicion` VARCHAR(45) NOT NULL,
  `peso` INT NOT NULL,
  `origen_idorigen` INT NOT NULL,
  PRIMARY KEY (`codigo`, `origen_idorigen`),
  INDEX `fk_moneda_origen1_idx` (`origen_idorigen` ASC),
  CONSTRAINT `fk_moneda_origen1`
    FOREIGN KEY (`origen_idorigen`)
    REFERENCES `corpora1_franklinsgold`.`origen` (`idorigen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corpora1_franklinsgold`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpora1_franklinsgold`.`sucursal` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corpora1_franklinsgold`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpora1_franklinsgold`.`transaccion` (
  `usuario_idusuario` INT NOT NULL,
  `moneda_codigo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `sucursal_idsucursal` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `moneda_codigo`, `fecha`, `sucursal_idsucursal`),
  INDEX `fk_usuario_has_moneda_moneda1_idx` (`moneda_codigo` ASC),
  INDEX `fk_usuario_has_moneda_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_transaccion_sucursal1_idx` (`sucursal_idsucursal` ASC),
  CONSTRAINT `fk_usuario_has_moneda_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `corpora1_franklinsgold`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_moneda_moneda1`
    FOREIGN KEY (`moneda_codigo`)
    REFERENCES `corpora1_franklinsgold`.`moneda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaccion_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `corpora1_franklinsgold`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
