insert into origen (idorigen, nombre) values (1, 'Gastoúni');
insert into origen (idorigen, nombre) values (2, 'Tyler');
insert into origen (idorigen, nombre) values (3, 'Harbour Breton');
insert into origen (idorigen, nombre) values (4, 'Beška');
insert into origen (idorigen, nombre) values (5, 'Varennes');
insert into origen (idorigen, nombre) values (6, 'Dagkar');
insert into origen (idorigen, nombre) values (7, 'Citeureup');
insert into origen (idorigen, nombre) values (8, 'Tutayev');
insert into origen (idorigen, nombre) values (9, 'Tonota');
insert into origen (idorigen, nombre) values (10, 'Kadukandel');
