insert into sucursal (idsucursal, nombre, direccion) values (1, 'Kavār', 'Iran');
insert into sucursal (idsucursal, nombre, direccion) values (2, 'Kuala Lumpur', 'Malaysia');
insert into sucursal (idsucursal, nombre, direccion) values (3, 'Chortkiv', 'Ukraine');
insert into sucursal (idsucursal, nombre, direccion) values (4, 'Mesógi', 'Cyprus');
insert into sucursal (idsucursal, nombre, direccion) values (5, 'Byczyna', 'Poland');
insert into sucursal (idsucursal, nombre, direccion) values (6, 'Šentjur', 'Slovenia');
insert into sucursal (idsucursal, nombre, direccion) values (7, 'Krajan Craken', 'Indonesia');
insert into sucursal (idsucursal, nombre, direccion) values (8, 'Vide', 'Portugal');
insert into sucursal (idsucursal, nombre, direccion) values (9, 'Guashe', 'China');
insert into sucursal (idsucursal, nombre, direccion) values (10, 'Yangdi', 'China');
